server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:mem:testdb
    platform: h2  #optional
  h2:
    console:
      enabled: true
      path: /h2-console #optionl use for adding custom path


